Apply sed 's/Freenet/Hyphanet/g'
This doesn't include .po files because they aren't safe to edit with
sed; it gives errors like:

    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 98: ordinal not in range(128)

Text in paths shouldn't change - those changes are performed here and
reverted in the next commit. Except for links; those are manually
adjusted.